# -*- coding: utf-8 -*-
"""Python requests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7sKWvWDGszLg6gke5rLqoGfR06o89dU
"""

import requests
url='https://xkcd.com/353/'
req=requests.get(url)
print(req)
print(dir(req))  #will print all the methods and attributes associated with req(response object)

print(help(req)) #to get the detailed explaination of the methods and attributes of the object

req.text  #content of the response object

#getting the image
url='https://imgs.xkcd.com/comics/python.png'
req=requests.get(url)

print(req.content) #prints out bytes from that content

#writing our content to a file
with open('comic.png','wb') as f:
  f.write(req.content)

print(req.status_code)

req.ok

req.headers

#using httpbin.org
payload={'page':2,'count':25}
url='http://httpbin.org/get'
req=requests.get(url,params=payload)

req.text

req.url

#if we want to post some data to the route
payload={'username':'ushna','password':'testing'}
url='http://httpbin.org/post'
req=requests.post(url,data=payload)
req.text #we are getting a json response from the httpsbin

#instead of text attribute we can use json method on req which is a json response
#json() will convert that response to python dectionary
print(type(req))
req.json()

url='http://httpbin.org/basic-auth/ushna/testing'
req=requests.get(url,auth=('ushna','testing'))
print(req.text)

#set time out with a request
url='http://httpbin.org/delay/6'
req=requests.get(url,timeout=3)
print(req)



